// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOcTQZ07thDdPn-BdZ_6OC-alneYSk65Q',
    appId: '1:779730882356:web:64ca666c2772452176df61',
    messagingSenderId: '779730882356',
    projectId: 'drawinglog-oaks-sye-sp26',
    authDomain: 'drawinglog-oaks-sye-sp26.firebaseapp.com',
    databaseURL: 'https://drawinglog-oaks-sye-sp26-default-rtdb.firebaseio.com',
    storageBucket: 'drawinglog-oaks-sye-sp26.firebasestorage.app',
    measurementId: 'G-4RX97B6JZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7x1LT-xkFxI-RkrxNo6mGUWX-HLgSNEY',
    appId: '1:779730882356:android:c896c84916c792ff76df61',
    messagingSenderId: '779730882356',
    projectId: 'drawinglog-oaks-sye-sp26',
    databaseURL: 'https://drawinglog-oaks-sye-sp26-default-rtdb.firebaseio.com',
    storageBucket: 'drawinglog-oaks-sye-sp26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLgUI1wUcYnzihPvcRGo63z37qbaCv4bU',
    appId: '1:779730882356:ios:b862695f3c34e42676df61',
    messagingSenderId: '779730882356',
    projectId: 'drawinglog-oaks-sye-sp26',
    databaseURL: 'https://drawinglog-oaks-sye-sp26-default-rtdb.firebaseio.com',
    storageBucket: 'drawinglog-oaks-sye-sp26.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLgUI1wUcYnzihPvcRGo63z37qbaCv4bU',
    appId: '1:779730882356:ios:b862695f3c34e42676df61',
    messagingSenderId: '779730882356',
    projectId: 'drawinglog-oaks-sye-sp26',
    databaseURL: 'https://drawinglog-oaks-sye-sp26-default-rtdb.firebaseio.com',
    storageBucket: 'drawinglog-oaks-sye-sp26.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOcTQZ07thDdPn-BdZ_6OC-alneYSk65Q',
    appId: '1:779730882356:web:8b79e69bd30e14ce76df61',
    messagingSenderId: '779730882356',
    projectId: 'drawinglog-oaks-sye-sp26',
    authDomain: 'drawinglog-oaks-sye-sp26.firebaseapp.com',
    databaseURL: 'https://drawinglog-oaks-sye-sp26-default-rtdb.firebaseio.com',
    storageBucket: 'drawinglog-oaks-sye-sp26.firebasestorage.app',
    measurementId: 'G-5N4H49S7MD',
  );
}
